USEMODULE_INCLUDES_coap_suit := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))/include
USEMODULE_INCLUDES += $(USEMODULE_INCLUDES_coap_suit)

# Required for SUIT updates to work with gcoap
CFLAGS += -DGCOAP_PDU_BUF_SIZE=256
