# This must be a different name than 'board' as it is implemented by 'native'
USEMODULE += board_enviro_samr21_xpro

# Include all sensor modules by default
ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += io1_xplained
  USEMODULE += sgp30
  DISABLE_MODULE += sgp30_strict
  USEMODULE += sm_pwm_01c
  USEMODULE += sm_pwm_01c_ma
endif

include $(RIOTBOARD)/samr21-xpro/Makefile.dep
