# This must be a different name than 'board' as it is implemented by 'native'
USEMODULE += board_enviro_samr21

# Include all sensor modules by default

ifneq (1, $(RIOTBOOT_BUILD))
  USEMODULE += io1_xplained
  USEMODULE += ccs811
  USEMODULE += sm_pwm_01c
  USEMODULE += sm_pwm_01c_ma
  EXTERNAL_MODULE_DIRS += $(TREEBASE)/drivers/sm_pwm_01c
endif

include $(RIOTBOARD)/samr21-xpro/Makefile.dep
