# This must be a different name than 'board' as it is implemented by 'native'
USEMODULE += board_enviro_nrf52840

ifneq (1,$(RIOTBOOT_BUILD))
  USEMODULE += stdio_cdc_acm
endif
ifneq (,$(filter saul_default,$(USEMODULE)))
  USEMODULE += bme280_i2c
endif

include $(RIOTBOARD)/feather-nrf52840/Makefile.dep
