ifeq (1, $(USE_SUIT))
  USEMODULE += coap_suit
  USEMODULE += suitreg
endif

ifeq (1,$(USE_ETHOS))
  USEMODULE += stdio_ethos
  USEMODULE += gnrc_uhcpc
endif

ifneq (,$(filter coap_%,$(USEMODULE)))
  # Include packages that pull up and auto-init the link layer.
  # NOTE: 6LoWPAN will be included if IEEE802.15.4 devices are present
  USEMODULE += gnrc_netdev_default
  USEMODULE += auto_init_gnrc_netif
  # Specify the mandatory networking modules for IPv6 and UDP
  USEMODULE += gnrc_ipv6_default
  # Additional networking modules that can be dropped if not needed
  USEMODULE += gnrc_sock_udp
  # Add echo module, can be removed
  USEMODULE += gnrc_icmpv6_echo
endif

ifneq (,$(filter coap_%,$(USEMODULE)))
  USEMODULE += gcoap
  FEATURES_OPTIONAL += puf_sram
endif

ifneq (,$(filter shell_common,$(USEMODULE)))
  USEMODULE += shell_commands
  USEMODULE += shell
  USEMODULE += ps
endif

