PSEUDOMODULES += shell_common

ifeq (1, $(USE_SUIT))
  USEMODULE += coap_suit
endif

ifeq (1, $(USE_TFT))
  CFLAGS += -DSUIT_STATUS_SUBS
  USEMODULE += tft_display
  FEATURES_REQUIRED += periph_gpio periph_spi
ifeq (1, $(USE_SUIT))
  USEMODULE += suitreg
endif
endif

ifneq (,$(filter coap_% mqtt_%,$(USEMODULE)))
  # Include packages that pull up and auto-init the link layer.
  # NOTE: 6LoWPAN will be included if IEEE802.15.4 devices are present
  USEMODULE += gnrc_netdev_default
  USEMODULE += auto_init_gnrc_netif
  # Specify the mandatory networking modules for IPv6 and UDP
  USEMODULE += gnrc_ipv6_default
  # Additional networking modules that can be dropped if not needed
  USEMODULE += gnrc_sock_udp
  # lower pktbuf size a little
  CFLAGS += -DGNRC_PKTBUF_SIZE=2000

  ifeq (1,$(USE_ETHOS))
    TAP ?= tap0
    IPV6_PREFIX ?= 2001:db8::/64

    GNRC_NETIF_NUMOF := 2
    USEMODULE += ethos
    USEMODULE += stdio_uart_rx
    USEMODULE += gnrc_uhcpc

    # ethos baudrate can be configured from make command
    ETHOS_BAUDRATE ?= 115200
    CFLAGS += -DETHOS_BAUDRATE=$(ETHOS_BAUDRATE) -DUSE_ETHOS_FOR_STDIO

    TERMDEPS += host-tools
    TERMPROG ?= sudo sh $(RIOTTOOLS)/ethos/start_network.sh
    TERMFLAGS ?= $(PORT) $(TAP) $(IPV6_PREFIX)
  endif
endif

ifneq (,$(filter coap_%,$(USEMODULE)))
  USEMODULE += gcoap
endif

ifneq (,$(filter mqtt_%,$(USEMODULE)))
  USEMODULE += emcute
endif

ifneq (,$(filter shell_common,$(USEMODULE)))
  USEMODULE += shell_commands
  USEMODULE += shell
  USEMODULE += ps
endif

ifneq (,$(filter tft_display,$(USEMODULE)))
  USEPKG += ucglib
endif
